# Use an official Python runtime as a parent image
FROM python:3.9

# Set the working directory to /app
WORKDIR /app

# Copy the application code into the container
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Command to start hwunit application 
CMD ["python", "-u", "TemperatureHardwareUnit/TemperatureHardwareUnit.py"]
